name: Prettier Action

# This action works with pull requests and pushes
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - run: pnpm install

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  commit_message: "ci: prettify code"
                  prettier_options: --write "**/*.{php,ts,tsx}""
                  prettier_plugins: "@prettier/plugin-php prettier-plugin-tailwindcss"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
